/**
 * zk-verifier.ts — Server-side ZK proof verification for X402 ZK Mesh
 *
 * Dual-path verification:
 *   1. On-chain: Soroban verifier contract on Stellar Testnet (Protocol 27)
 *   2. Local fallback: snarkjs verification with local VK files
 */

import * as fs from "fs";
import * as path from "path";
import * as StellarSDK from "@stellar/stellar-sdk";
import { Spec } from "@stellar/stellar-sdk/contract";
// @ts-expect-error snarkjs doesn't ship proper TS types
import * as snarkjs from "snarkjs";
import type { CircuitName, ZKProof } from "./zk-prover";

const VK_DIR = path.join(process.cwd(), "circuits", "keys");
const VERIFIER_WASM_DIR = path.join(process.cwd(), "contracts", "target", "wasm32v1-none", "release");

/**
 * Deployed Soroban contract IDs on Stellar Testnet (Protocol 27)
 * Real BN254 Groth16 verifiers generated by soroban-verifier-gen
 * Each contract has its circuit's VK hardcoded and calls bn254.pairing_check()
 */
const CONTRACT_IDS: Record<string, string> = {
  deposit_commitment: process.env.ZK_VERIFIER_DEPOSIT || "CAEWGDTGCIDBFKLSYW5EYANR227JXO7G4WGGHYD5WTGZMYL7YNPP44UE",
  membership_proof: process.env.ZK_VERIFIER_MEMBERSHIP || "CBX3GKLGB73LKYGWDWNIIJO7MDIZHE73KS2SRZWBC3TBVYKYT6ANCE5Y",
  execution_proof: process.env.ZK_VERIFIER_EXECUTION || "CCJRM2X4Y7RPUHL5GE6LXSPWQH2LLBV6LGHB4CXPJ4SCWXL5PP6JIQKQ",
};

const PRIVACY_POOL_ID = "CDGTAPVSKG5EWJIJUCGDHFXJ5YWDKEOAICVFBFLZ7QPAX5HII2IBB74X";
const GUILD_REGISTRY_ID = "CDJKNLOK5U4N7IPLDDX2Y3FPMSS6ERREGU7VXCXDVANC7YUAB56ZD7ZB";

const SOROBAN_RPC = process.env.STELLAR_RPC_URL || process.env.SOROBAN_RPC_URL || "https://soroban-testnet.stellar.org:443";
const VERIFIER_WASM: Record<string, string> = {
  deposit_commitment: "verifier_deposit.wasm",
  membership_proof: "verifier_membership.wasm",
  execution_proof: "verifier_execution.wasm",
};

/**
 * Load a verification key from the filesystem.
 */
function loadVerificationKey(circuit: CircuitName): object {
  const vkPath = path.join(VK_DIR, `${circuit}_vk.json`);
  const raw = fs.readFileSync(vkPath, "utf-8");
  return JSON.parse(raw);
}

/**
 * Verify a Groth16 proof — tries Soroban on-chain first, falls back to local snarkjs.
 *
 * @returns verification result with method indicator
 */
export async function verifyProof(
  circuit: CircuitName,
  proof: ZKProof["proof"],
  publicSignals: string[]
): Promise<{
  valid: boolean;
  method: "local" | "soroban";
  contractId?: string;
  txHash?: string;
}> {
  const contractId = CONTRACT_IDS[circuit];

  // Try on-chain verification first
  if (contractId && process.env.ZK_VERIFY_ON_CHAIN !== "false") {
    try {
      return await verifySoroban(circuit, proof, publicSignals);
    } catch {
      // Soroban call failed — fall back to local
      console.warn(`[zk-verifier] Soroban call failed for ${circuit}, using local fallback`);
    }
  }

  // Local verification via snarkjs
  const vk = loadVerificationKey(circuit);
  const valid = await snarkjs.groth16.verify(vk, publicSignals, proof);

  return {
    valid,
    method: "local",
    contractId,
  };
}

/**
 * Verify proof via Soroban verifier contract simulation.
 *
 * Uses Stellar SDK to build a real invokeHostFunction transaction XDR and
 * Stellar Testnet RPC simulateTransaction to invoke verify_proof.
 * The contract does real BN254 g1_mul → g1_add → pairing_check.
 *
 * If simulate fails (network issue, budget exceeded), caller falls back to local.
 */
async function verifySoroban(
  circuit: CircuitName,
  proof: ZKProof["proof"],
  publicSignals: string[]
): Promise<{
  valid: boolean;
  method: "soroban";
  contractId: string;
  txHash: string;
}> {
  const contractId = CONTRACT_IDS[circuit];
  const spec = loadVerifierSpec(circuit);
  const args = spec.funcArgsToScVals("verify_proof", {
    proof: proofToContractInput(proof),
    pub_signals: publicSignals.map(String),
  });

  const server = new StellarSDK.rpc.Server(SOROBAN_RPC);
  const source = new StellarSDK.Account(getSimulationSource(), "0");
  const contract = new StellarSDK.Contract(contractId);
  const tx = new StellarSDK.TransactionBuilder(source, {
    fee: process.env.STELLAR_SIMULATION_FEE || "100000",
    networkPassphrase: StellarSDK.Networks.TESTNET,
  })
    .addOperation(contract.call("verify_proof", ...args))
    .setTimeout(30)
    .build();

  const simulation = await server.simulateTransaction(tx);

  if (StellarSDK.rpc.Api.isSimulationError(simulation)) {
    throw new Error(`Soroban simulation failed: ${simulation.error}`);
  }

  const returnVal = simulation.result?.retval;
  if (!returnVal) {
    throw new Error("Soroban simulation did not return a verifier result.");
  }

  const result = spec.funcResToNative("verify_proof", returnVal);
  const valid = normalizeSorobanBool(result);

  return {
    valid,
    method: "soroban",
    contractId,
    txHash: `sim-ledger-${simulation.latestLedger}`,
  };
}

function loadVerifierSpec(circuit: CircuitName): Spec {
  const wasmName = VERIFIER_WASM[circuit];
  if (!wasmName) {
    throw new Error(`No verifier WASM configured for ${circuit}`);
  }
  const wasmPath = path.join(VERIFIER_WASM_DIR, wasmName);
  return Spec.fromWasm(fs.readFileSync(wasmPath));
}

function proofToContractInput(proof: ZKProof["proof"]) {
  return {
    a: g1ToBase64(proof.pi_a),
    b: g2ToBase64(proof.pi_b),
    c: g1ToBase64(proof.pi_c),
  };
}

function g1ToBase64(point: [string, string] | string[]): string {
  return Buffer.from(toBigEndianHex(point[0]) + toBigEndianHex(point[1]), "hex").toString("base64");
}

function g2ToBase64(point: [[string, string], [string, string]] | string[][]): string {
  return Buffer.from(
    toBigEndianHex(point[0][1]) +
      toBigEndianHex(point[0][0]) +
      toBigEndianHex(point[1][1]) +
      toBigEndianHex(point[1][0]),
    "hex",
  ).toString("base64");
}

function toBigEndianHex(val: string): string {
  return BigInt(val).toString(16).padStart(64, "0");
}

function getSimulationSource(): string {
  const candidates = [
    process.env.STELLAR_DEMO_SIM_SOURCE,
    process.env.STELLAR_PLATFORM_WALLET,
    process.env.ZK_VERIFIER_RELAYER_PUBLIC_KEY,
  ].filter((value): value is string => !!value && value.startsWith("G"));
  return candidates[0] || "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF";
}

function normalizeSorobanBool(result: unknown): boolean {
  if (typeof result === "boolean") {
    return result;
  }
  if (result && typeof result === "object") {
    if ("value" in result) {
      return normalizeSorobanBool((result as { value: unknown }).value);
    }
    if ("ok" in result) {
      return normalizeSorobanBool((result as { ok: unknown }).ok);
    }
  }
  if (result instanceof StellarSDK.xdr.ScVal) {
    return normalizeSorobanBool(StellarSDK.scValToNative(result));
  }
  throw new Error(`Unexpected Soroban verifier return value: ${JSON.stringify(result)}`);
}

/**
 * Get all deployed contract addresses.
 */
export function getContractAddresses() {
  return {
    verifier: CONTRACT_IDS,
    privacyPool: PRIVACY_POOL_ID,
    guildRegistry: GUILD_REGISTRY_ID,
    rpc: SOROBAN_RPC,
    network: "testnet",
    protocol: 27,
  };
}

/**
 * Extract the commitment and nullifier hash from deposit proof public signals.
 */
export function parseDepositSignals(publicSignals: string[]): {
  commitment: string;
  nullifierHash: string;
} {
  return {
    commitment: publicSignals[0],
    nullifierHash: publicSignals[1],
  };
}

/**
 * Extract the Merkle root from membership proof public signals.
 */
export function parseMembershipSignals(publicSignals: string[]): {
  root: string;
} {
  return {
    root: publicSignals[0],
  };
}

/**
 * Extract the execution ID from execution proof public signals.
 */
export function parseExecutionSignals(publicSignals: string[]): {
  executionId: string;
} {
  return {
    executionId: publicSignals[0],
  };
}
