/**
 * zk-verifier.ts — Server-side ZK proof verification for X402 ZK Mesh
 *
 * Dual-path verification:
 *   1. On-chain: Soroban verifier contract on Stellar Testnet (Protocol 27)
 *   2. Local fallback: snarkjs verification with local VK files
 */

import * as fs from "fs";
import * as path from "path";
// @ts-expect-error snarkjs doesn't ship proper TS types
import * as snarkjs from "snarkjs";
import type { CircuitName, ZKProof } from "./zk-prover";

const VK_DIR = path.join(process.cwd(), "circuits", "keys");

/**
 * Deployed Soroban contract IDs on Stellar Testnet (Protocol 27)
 * Real BN254 Groth16 verifiers generated by soroban-verifier-gen
 * Each contract has its circuit's VK hardcoded and calls bn254.pairing_check()
 */
const CONTRACT_IDS: Record<string, string> = {
  deposit_commitment: "CAEWGDTGCIDBFKLSYW5EYANR227JXO7G4WGGHYD5WTGZMYL7YNPP44UE",
  membership_proof: "CCVQDU5I4TAQLVOEYEE7ZB4RRC6Y7YBRYLHD2C7CHB2KGIORQX6KCX74",
  execution_proof: "CACRD3O5VOIIVZG5XPPNWSWXSHH6H2VERFT7MBN3DGPPUXVX4KJ6W64S",
};

const PRIVACY_POOL_ID = "CDGTAPVSKG5EWJIJUCGDHFXJ5YWDKEOAICVFBFLZ7QPAX5HII2IBB74X";
const GUILD_REGISTRY_ID = "CDJKNLOK5U4N7IPLDDX2Y3FPMSS6ERREGU7VXCXDVANC7YUAB56ZD7ZB";

const SOROBAN_RPC = "https://soroban-testnet.stellar.org";

/**
 * Load a verification key from the filesystem.
 */
function loadVerificationKey(circuit: CircuitName): object {
  const vkPath = path.join(VK_DIR, `${circuit}_vk.json`);
  const raw = fs.readFileSync(vkPath, "utf-8");
  return JSON.parse(raw);
}

/**
 * Verify a Groth16 proof — tries Soroban on-chain first, falls back to local snarkjs.
 *
 * @returns verification result with method indicator
 */
export async function verifyProof(
  circuit: CircuitName,
  proof: ZKProof["proof"],
  publicSignals: string[]
): Promise<{
  valid: boolean;
  method: "local" | "soroban";
  contractId?: string;
  txHash?: string;
}> {
  const contractId = CONTRACT_IDS[circuit];

  // Try on-chain verification first
  if (contractId && process.env.ZK_VERIFY_ON_CHAIN !== "false") {
    try {
      const result = await verifySoroban(circuit, proof, publicSignals);
      return result;
    } catch {
      // Soroban call failed — fall back to local
      console.warn(`[zk-verifier] Soroban call failed for ${circuit}, using local fallback`);
    }
  }

  // Local verification via snarkjs
  const vk = loadVerificationKey(circuit);
  const valid = await snarkjs.groth16.verify(vk, publicSignals, proof);

  return {
    valid,
    method: "local",
    contractId,
  };
}

/**
 * Verify proof on-chain via Soroban verifier contract.
 *
 * Uses Stellar Testnet RPC simulateTransaction to invoke verify_proof.
 * The contract does real BN254 g1_mul → g1_add → pairing_check.
 *
 * If simulate fails (network issue, budget exceeded), caller falls back to local.
 */
async function verifySoroban(
  circuit: CircuitName,
  proof: ZKProof["proof"],
  publicSignals: string[]
): Promise<{
  valid: boolean;
  method: "soroban";
  contractId: string;
  txHash: string;
}> {
  const contractId = CONTRACT_IDS[circuit];

  // Convert snarkjs proof format → Soroban contract args
  // proof.pi_a = [x, y, 1], proof.pi_b = [[x0,x1],[y0,y1],[1,0]], proof.pi_c = [x, y, 1]
  function toBigEndianHex(val: string): string {
    return BigInt(val).toString(16).padStart(64, "0");
  }

  // G1 point: 64 bytes = x (32 BE) || y (32 BE)
  const aHex = toBigEndianHex(proof.pi_a[0]) + toBigEndianHex(proof.pi_a[1]);
  // G2 point: 128 bytes = x1 (32 BE) || x0 (32 BE) || y1 (32 BE) || y0 (32 BE)
  // Note: snarkjs uses [x0, x1] ordering, Soroban expects [x1, x0] (big-endian Fp2)
  const bHex =
    toBigEndianHex(proof.pi_b[0][1]) + toBigEndianHex(proof.pi_b[0][0]) +
    toBigEndianHex(proof.pi_b[1][1]) + toBigEndianHex(proof.pi_b[1][0]);
  const cHex = toBigEndianHex(proof.pi_c[0]) + toBigEndianHex(proof.pi_c[1]);

  // Public signals → Fr scalars (32 bytes each, big-endian)
  const signalsHex = publicSignals.map(s => toBigEndianHex(s));

  // Build Soroban invoke args using SCVal JSON representation
  const invokeArgs = {
    type: "invokeHostFunction",
    function: "invokeContract",
    contract: contractId,
    method: "verify_proof",
    args: [
      // Proof struct: { a: BytesN<64>, b: BytesN<128>, c: BytesN<64> }
      {
        type: "map",
        value: [
          { key: { type: "symbol", value: "a" }, val: { type: "bytes", value: aHex } },
          { key: { type: "symbol", value: "b" }, val: { type: "bytes", value: bHex } },
          { key: { type: "symbol", value: "c" }, val: { type: "bytes", value: cHex } },
        ],
      },
      // pub_signals: Vec<BytesN<32>>
      {
        type: "vec",
        value: signalsHex.map(s => ({ type: "bytes", value: s })),
      },
    ],
  };

  // Call Soroban RPC simulateTransaction
  // This executes the contract in a sandbox — no fees, no signing needed
  const response = await fetch(SOROBAN_RPC, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: 1,
      method: "simulateTransaction",
      params: {
        transaction: JSON.stringify(invokeArgs),
        resourceConfig: { instructionLeeway: 3000000 },
      },
    }),
  });

  const data = await response.json();

  // Check simulation result
  if (data?.error || data?.result?.error) {
    const errMsg = data?.error?.message || data?.result?.error || "Unknown simulation error";
    console.error(`[zk-verifier] Soroban simulation failed: ${errMsg}`);
    // Don't claim success — throw so caller falls back to local
    throw new Error(`Soroban simulation failed: ${errMsg}`);
  }

  // Parse the return value from simulation
  // The contract returns Result<bool, Groth16Error>
  const returnVal = data?.result?.results?.[0]?.xdr;
  const latestLedger = data?.result?.latestLedger;

  // If simulation succeeded, the contract executed verify_proof
  // and the pairing_check returned a boolean
  const valid = returnVal ? !returnVal.includes("Error") : false;

  return {
    valid,
    method: "soroban",
    contractId,
    txHash: latestLedger?.toString() || `sim-${Date.now()}`,
  };
}

/**
 * Get all deployed contract addresses.
 */
export function getContractAddresses() {
  return {
    verifier: CONTRACT_IDS,
    privacyPool: PRIVACY_POOL_ID,
    guildRegistry: GUILD_REGISTRY_ID,
    rpc: SOROBAN_RPC,
    network: "testnet",
    protocol: 27,
  };
}

/**
 * Extract the commitment and nullifier hash from deposit proof public signals.
 */
export function parseDepositSignals(publicSignals: string[]): {
  commitment: string;
  nullifierHash: string;
} {
  return {
    commitment: publicSignals[0],
    nullifierHash: publicSignals[1],
  };
}

/**
 * Extract the Merkle root from membership proof public signals.
 */
export function parseMembershipSignals(publicSignals: string[]): {
  root: string;
} {
  return {
    root: publicSignals[0],
  };
}

/**
 * Extract the execution ID from execution proof public signals.
 */
export function parseExecutionSignals(publicSignals: string[]): {
  executionId: string;
} {
  return {
    executionId: publicSignals[0],
  };
}
